# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "MySensors mys2MQTT"
version: "1.4"
slug: mys2MQTT
description: "MySensors to MQTT"
url: "https://github.com/mmaura/hassio-addons"
arch:
  - armv7
  - amd64
  - i386
init: false
services:
  need:
    - mqtt
backup: hot
map:
  - addon_config:rw
options:
  device: "/dev/ttyACM0"
schema:
  device(subsystem=tty): "str?"
image: "ghcr.io/mycontroller/{arch}-2mqtt"
